#Jekyll configuration
name: FearlessPython
description: Tutorials about Basics of Python Programming, by FearlessPython.
baseurl: "/Basics-of-Python"
url: "https://github.com/FearlessPython"
markdown: GFM # GitHub Flavored Markdown